/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as LeaderSlugRouteImport } from './routes/leader.$slug'
import { Route as DashboardPortfolioRouteImport } from './routes/dashboard.portfolio'
import { Route as DashboardAccountRouteImport } from './routes/dashboard.account'
import { Route as CategoryCategorySlugRouteImport } from './routes/category.$categorySlug'
import { Route as LeaderSlugProfessionalExpertiseRouteImport } from './routes/leader.$slug_.professional-expertise'
import { Route as CategoryCategorySlugSubcategorySlugRouteImport } from './routes/category.$categorySlug.$subcategorySlug'

const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const LeaderSlugRoute = LeaderSlugRouteImport.update({
  id: '/leader/$slug',
  path: '/leader/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPortfolioRoute = DashboardPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const CategoryCategorySlugRoute = CategoryCategorySlugRouteImport.update({
  id: '/category/$categorySlug',
  path: '/category/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderSlugProfessionalExpertiseRoute =
  LeaderSlugProfessionalExpertiseRouteImport.update({
    id: '/leader/$slug_/professional-expertise',
    path: '/leader/$slug/professional-expertise',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoryCategorySlugSubcategorySlugRoute =
  CategoryCategorySlugSubcategorySlugRouteImport.update({
    id: '/$subcategorySlug',
    path: '/$subcategorySlug',
    getParentRoute: () => CategoryCategorySlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRouteWithChildren
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/leader/$slug': typeof LeaderSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/category/$categorySlug/$subcategorySlug': typeof CategoryCategorySlugSubcategorySlugRoute
  '/leader/$slug/professional-expertise': typeof LeaderSlugProfessionalExpertiseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRouteWithChildren
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/leader/$slug': typeof LeaderSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/category/$categorySlug/$subcategorySlug': typeof CategoryCategorySlugSubcategorySlugRoute
  '/leader/$slug/professional-expertise': typeof LeaderSlugProfessionalExpertiseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRouteWithChildren
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/leader/$slug': typeof LeaderSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/category/$categorySlug/$subcategorySlug': typeof CategoryCategorySlugSubcategorySlugRoute
  '/leader/$slug_/professional-expertise': typeof LeaderSlugProfessionalExpertiseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply'
    | '/dashboard'
    | '/login'
    | '/set-password'
    | '/category/$categorySlug'
    | '/dashboard/account'
    | '/dashboard/portfolio'
    | '/leader/$slug'
    | '/dashboard/'
    | '/category/$categorySlug/$subcategorySlug'
    | '/leader/$slug/professional-expertise'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apply'
    | '/login'
    | '/set-password'
    | '/category/$categorySlug'
    | '/dashboard/account'
    | '/dashboard/portfolio'
    | '/leader/$slug'
    | '/dashboard'
    | '/category/$categorySlug/$subcategorySlug'
    | '/leader/$slug/professional-expertise'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apply'
    | '/dashboard'
    | '/login'
    | '/set-password'
    | '/category/$categorySlug'
    | '/dashboard/account'
    | '/dashboard/portfolio'
    | '/leader/$slug'
    | '/dashboard/'
    | '/category/$categorySlug/$subcategorySlug'
    | '/leader/$slug_/professional-expertise'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApplyRoute: typeof ApplyRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetPasswordRoute: typeof SetPasswordRoute
  CategoryCategorySlugRoute: typeof CategoryCategorySlugRouteWithChildren
  LeaderSlugRoute: typeof LeaderSlugRoute
  LeaderSlugProfessionalExpertiseRoute: typeof LeaderSlugProfessionalExpertiseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/leader/$slug': {
      id: '/leader/$slug'
      path: '/leader/$slug'
      fullPath: '/leader/$slug'
      preLoaderRoute: typeof LeaderSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/portfolio': {
      id: '/dashboard/portfolio'
      path: '/portfolio'
      fullPath: '/dashboard/portfolio'
      preLoaderRoute: typeof DashboardPortfolioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/category/$categorySlug': {
      id: '/category/$categorySlug'
      path: '/category/$categorySlug'
      fullPath: '/category/$categorySlug'
      preLoaderRoute: typeof CategoryCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leader/$slug_/professional-expertise': {
      id: '/leader/$slug_/professional-expertise'
      path: '/leader/$slug/professional-expertise'
      fullPath: '/leader/$slug/professional-expertise'
      preLoaderRoute: typeof LeaderSlugProfessionalExpertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categorySlug/$subcategorySlug': {
      id: '/category/$categorySlug/$subcategorySlug'
      path: '/$subcategorySlug'
      fullPath: '/category/$categorySlug/$subcategorySlug'
      preLoaderRoute: typeof CategoryCategorySlugSubcategorySlugRouteImport
      parentRoute: typeof CategoryCategorySlugRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardPortfolioRoute: typeof DashboardPortfolioRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardPortfolioRoute: DashboardPortfolioRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface CategoryCategorySlugRouteChildren {
  CategoryCategorySlugSubcategorySlugRoute: typeof CategoryCategorySlugSubcategorySlugRoute
}

const CategoryCategorySlugRouteChildren: CategoryCategorySlugRouteChildren = {
  CategoryCategorySlugSubcategorySlugRoute:
    CategoryCategorySlugSubcategorySlugRoute,
}

const CategoryCategorySlugRouteWithChildren =
  CategoryCategorySlugRoute._addFileChildren(CategoryCategorySlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApplyRoute: ApplyRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SetPasswordRoute: SetPasswordRoute,
  CategoryCategorySlugRoute: CategoryCategorySlugRouteWithChildren,
  LeaderSlugRoute: LeaderSlugRoute,
  LeaderSlugProfessionalExpertiseRoute: LeaderSlugProfessionalExpertiseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
