/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeaderSlugRouteImport } from './routes/leader.$slug'
import { Route as CategoryCategorySlugRouteImport } from './routes/category.$categorySlug'
import { Route as LeaderSlugProfessionalExpertiseRouteImport } from './routes/leader.$slug_.professional-expertise'
import { Route as CategoryCategorySlugSubcategorySlugRouteImport } from './routes/category.$categorySlug.$subcategorySlug'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderSlugRoute = LeaderSlugRouteImport.update({
  id: '/leader/$slug',
  path: '/leader/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategorySlugRoute = CategoryCategorySlugRouteImport.update({
  id: '/category/$categorySlug',
  path: '/category/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderSlugProfessionalExpertiseRoute =
  LeaderSlugProfessionalExpertiseRouteImport.update({
    id: '/leader/$slug_/professional-expertise',
    path: '/leader/$slug/professional-expertise',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoryCategorySlugSubcategorySlugRoute =
  CategoryCategorySlugSubcategorySlugRouteImport.update({
    id: '/$subcategorySlug',
    path: '/$subcategorySlug',
    getParentRoute: () => CategoryCategorySlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRouteWithChildren
  '/leader/$slug': typeof LeaderSlugRoute
  '/category/$categorySlug/$subcategorySlug': typeof CategoryCategorySlugSubcategorySlugRoute
  '/leader/$slug/professional-expertise': typeof LeaderSlugProfessionalExpertiseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRouteWithChildren
  '/leader/$slug': typeof LeaderSlugRoute
  '/category/$categorySlug/$subcategorySlug': typeof CategoryCategorySlugSubcategorySlugRoute
  '/leader/$slug/professional-expertise': typeof LeaderSlugProfessionalExpertiseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRouteWithChildren
  '/leader/$slug': typeof LeaderSlugRoute
  '/category/$categorySlug/$subcategorySlug': typeof CategoryCategorySlugSubcategorySlugRoute
  '/leader/$slug_/professional-expertise': typeof LeaderSlugProfessionalExpertiseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/category/$categorySlug'
    | '/leader/$slug'
    | '/category/$categorySlug/$subcategorySlug'
    | '/leader/$slug/professional-expertise'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/category/$categorySlug'
    | '/leader/$slug'
    | '/category/$categorySlug/$subcategorySlug'
    | '/leader/$slug/professional-expertise'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/category/$categorySlug'
    | '/leader/$slug'
    | '/category/$categorySlug/$subcategorySlug'
    | '/leader/$slug_/professional-expertise'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CategoryCategorySlugRoute: typeof CategoryCategorySlugRouteWithChildren
  LeaderSlugRoute: typeof LeaderSlugRoute
  LeaderSlugProfessionalExpertiseRoute: typeof LeaderSlugProfessionalExpertiseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leader/$slug': {
      id: '/leader/$slug'
      path: '/leader/$slug'
      fullPath: '/leader/$slug'
      preLoaderRoute: typeof LeaderSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categorySlug': {
      id: '/category/$categorySlug'
      path: '/category/$categorySlug'
      fullPath: '/category/$categorySlug'
      preLoaderRoute: typeof CategoryCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leader/$slug_/professional-expertise': {
      id: '/leader/$slug_/professional-expertise'
      path: '/leader/$slug/professional-expertise'
      fullPath: '/leader/$slug/professional-expertise'
      preLoaderRoute: typeof LeaderSlugProfessionalExpertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categorySlug/$subcategorySlug': {
      id: '/category/$categorySlug/$subcategorySlug'
      path: '/$subcategorySlug'
      fullPath: '/category/$categorySlug/$subcategorySlug'
      preLoaderRoute: typeof CategoryCategorySlugSubcategorySlugRouteImport
      parentRoute: typeof CategoryCategorySlugRoute
    }
  }
}

interface CategoryCategorySlugRouteChildren {
  CategoryCategorySlugSubcategorySlugRoute: typeof CategoryCategorySlugSubcategorySlugRoute
}

const CategoryCategorySlugRouteChildren: CategoryCategorySlugRouteChildren = {
  CategoryCategorySlugSubcategorySlugRoute:
    CategoryCategorySlugSubcategorySlugRoute,
}

const CategoryCategorySlugRouteWithChildren =
  CategoryCategorySlugRoute._addFileChildren(CategoryCategorySlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CategoryCategorySlugRoute: CategoryCategorySlugRouteWithChildren,
  LeaderSlugRoute: LeaderSlugRoute,
  LeaderSlugProfessionalExpertiseRoute: LeaderSlugProfessionalExpertiseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
